#!/bin/bash
str0="strat2=g_strsplit_set(strary2[m], \"\\t\", 0);
if (g_file_get_contents(strat2[1], &contents, NULL, &Err))
{
	strary=g_strsplit_set(contents, \"\\r\", 0);
	sal=g_strv_length(strary);
	{xp=g_array_new(FALSE, FALSE, sizeof(gdouble)); yp=g_array_new(FALSE, FALSE, sizeof(gdouble));}
	lc=lcib;
	for (k=kib; k<sal; k++)
	{
		if (!strary[k]) continue;
		g_strchug(strary[k]);
		if (!g_strcmp0(\"\", strary[k])) continue;
		if (!(g_ascii_isdigit(strary[k][0])|(g_str_has_prefix(strary[k],\"-\")))) continue;
		if ((lc++)<0) continue;
		strat=g_strsplit_set(strary[k], dm, 0);
		lcl=g_ascii_strtod(g_strstrip(strat[0]), NULL);
		g_array_append_val(xp, lcl);
		if (!strat[trc]) lcl=0;
		else lcl=g_ascii_strtod(g_strstrip(strat[trc]), NULL);
		g_array_append_val(yp, lcl);
		g_strfreev(strat);
	}
	g_strfreev(strary);
	lcl=g_ascii_strtod(g_strstrip(strat2[0]), NULL);
	if (lcl<xi) xi=lcl;
	else if (lcl>xf) xf=lcl;
	delp=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx);
	for (j=0; j<n; j++) yt[j]=0;"

str1="	{g_array_free(xp, TRUE); g_array_free(yp, TRUE);}
	fftw_execute(p);
	starp=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), n);
	for (j=0; j<n; j++) g_array_append_val(starp, star[j]);
	for (j=0; j<jdimx; j++)
	{
		vzt=g_array_index(starp, gdouble, j*zp);
		iv=g_array_index(delp, gdouble, j);
		if (iv<DZE) idelf=G_MAXDOUBLE;
		else idelf=1/iv;
		iv=g_array_index(zwa, gdouble, j)*idelf/2;
		for (l=1; l<iv; l++)
		{
			ivd=g_array_index(starp, gdouble, l+(j*zp));
			ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-l);
			vzt+=sqrt((ivd*ivd)+(ivdt*ivdt));
		}
		if (vzt<DZE) vzt=G_MAXDOUBLE;
		else vzt=l/vzt;
		for (k=0; k<kdimxf; k++)
		{
			g_array_append_val(x, lcl);
			sr=(gint) ceil(g_array_index(isra, gdouble, j+(k*jdimx))*idelf);
			sp=(gint) floor(g_array_index(ispa, gdouble, j+(k*jdimx))*idelf);
			tcn=g_array_index(tca, gdouble, j+(k*jdimx))*idelf;
			twd=g_array_index(twa, gdouble, j+(k*jdimx))*idelf/2;
			if ((sr<((zp-1)/2))&&(sp<(zp/2))&&((sp-sr)>1))
			{
				vt=g_array_index(starp, gdouble, sr+(j*zp));
				ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-sr);
				phia=atan2(ivdt, vt);
				vt=sqrt((vt*vt)+(ivdt*ivdt));
				ivd=g_array_index(starp, gdouble, sr+1+(j*zp));
				ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-sr-1);
				phio=-atan2(ivdt, ivd);
				phia+=phio;
				vt+=sqrt((ivd*ivd)+(ivdt*ivdt));
				{pn=0; cn=0; dst=0; ddp=0;}
				for (l=sr+2; l<=sp; l++)
				{
					ivd=g_array_index(starp, gdouble, l+(j*zp));
					ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-l);
					phi=atan2(ivdt, ivd);
					phio+=phi;
					vt+=sqrt((ivd*ivd)+(ivdt*ivdt));
					if (phio>G_PI) phio-=(MY_2PI);
					else if (phio<=NMY_PI) phio+=(MY_2PI);
					if (l>(tcn-twd+0.5))
					{
						if ((l-1)<=(tcn-twd))
						{
							tp=(((gdouble) l)-tcn-0.5)/twd;
							pn+=++tp;
							dst+=tp*phio;
						}
						else if (l<=(tcn+0.5))
						{
							tp=(((gdouble) l)-tcn-0.5)/twd;
							ct=(((gdouble) l)-tcn-1)/twd;
							pn+=++tp;
							dst+=tp*phio;
							cn+=++ct;
							phia+=phio;
							ddp+=ct*phia;
						}
						else if ((l-1)<=tcn)
						{
							tp=(tcn+0.5-((gdouble) l))/twd;
							ct=(((gdouble) l)-tcn-1)/twd;
							pn+=++tp;
							dst+=tp*phio;
							cn+=++ct;
							phia+=phio;
							ddp+=ct*phia;
						}
						else if (l<(tcn+twd+0.5))
						{
							tp=(tcn+0.5-((gdouble) l))/twd;
							ct=(tcn+1-((gdouble) l))/twd;
							pn+=++tp;
							dst+=tp*phio;
							cn+=++ct;
							phia+=phio;
							ddp+=ct*phia;
						}
						else if ((l-1)<(tcn+twd))
						{
							ct=(tcn+1-((gdouble) l))/twd;
							cn+=++ct;
							phia+=phio;
							ddp+=ct*phia;
						}
					}
					phia=-phio;
					phio=-phi;
				}
				pn*=NMY_2PI*g_array_index(delp, gdouble, j);
				if ((pn<DZE)&&(pn>NZE)) dst=G_MAXDOUBLE;
				else dst/=pn;
				cn*=NMY_2PI*g_array_index(delp, gdouble, j);
				cn*=G_PI*g_array_index(delp, gdouble, j);
				if ((cn<DZE)&&(cn>NZE)) ddp=G_MAXDOUBLE;
				else ddp=cn/ddp;
				vt*=vzt/(sp-sr+1);
			}
			else {vt=0; dst=0; ddp=0;}
			{g_array_append_val(vis, vt); g_array_append_val(doms, dst); g_array_append_val(chp, ddp);}
		}
	}
	{g_array_free(delp, TRUE); g_array_free(starp, TRUE);}
}
else
{
	str=g_strdup_printf(_(\"Loading failed for file: %s, Error: %s.\"), fin, (Err->message));
	gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
	{g_free(str); g_error_free(Err);}
}
{g_free(contents); g_strfreev(strat2);}"

str2="	{g_array_free(xp, TRUE); g_array_free(yp, TRUE);}
	fftw_execute(p);
	starp=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), n);
	for (j=0; j<n; j++) g_array_append_val(starp, star[j]);
	for (j=0; j<jdimx; j++)
	{
		vzt=g_array_index(starp, gdouble, j*zp);
		iv=g_array_index(delp, gdouble, j);
		if (iv<DZE) idelf=G_MAXDOUBLE;
		else idelf=1/iv;
		iv=g_array_index(zwa, gdouble, j)*idelf/2;
		for (l=1; l<iv; l++)
		{
			ivd=g_array_index(starp, gdouble, l+(j*zp));
			ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-l);
			vzt+=sqrt((ivd*ivd)+(ivdt*ivdt));
		}
		if (vzt<DZE) vzt=G_MAXDOUBLE;
		else vzt=l/vzt;
		for (k=0; k<kdimxf; k++)
		{
			g_array_append_val(x, lcl);
			sr=(gint) ceil(g_array_index(isra, gdouble, j+(k*jdimx))*idelf);
			sp=(gint) floor(g_array_index(ispa, gdouble, j+(k*jdimx))*idelf);
			tcn=g_array_index(tca, gdouble, j+(k*jdimx))*idelf;
			twd=g_array_index(twa, gdouble, j+(k*jdimx))*idelf/2;
			if ((sr<((zp/2)-1))&&(sp<(zp/2))&&((sp-sr)>0))
			{
				vt=g_array_index(starp, gdouble, sr+(j*zp));
				ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-sr);
				phio=-atan2(ivdt, vt);
				vt=sqrt((vt*vt)+(ivdt*ivdt));
				{dst=0; pn=0;}
				for (l=sr+1; l<=sp; l++)
				{
					ivd=g_array_index(starp, gdouble, l+(j*zp));
					ivdt=g_array_index(starp, gdouble, ((j+1)*zp)-l);
					phi=atan2(ivdt, ivd);
					phio+=phi;
					vt+=sqrt((ivd*ivd)+(ivdt*ivdt));
					if (phio>G_PI) phio-=(MY_2PI);
					else if (phio<=NMY_PI) phio+=(MY_2PI);
					if (l>(tcn-twd+0.5))
					{
						if (l<=(tcn+0.5))
						{
							tp=(((gdouble) l)-tcn-0.5)/twd;
							pn+=++tp;
							dst+=tp*phio;
						}
						else if (l<(tcn+twd+0.5))
						{
							tp=(tcn+0.5-((gdouble) l))/twd;
							pn+=++tp;
							dst+=tp*phio;
						}
					}
					phio=-phi;
				}
				pn*=NMY_2PI*g_array_index(delp, gdouble, j);
				if ((pn<DZE)&&(pn>NZE)) dst=G_MAXDOUBLE;
				else dst/=pn;
				vt*=vzt/(sp-sr+1);
			}
			else {vt=0; dst=0;}
			{g_array_append_val(vis, vt); g_array_append_val(doms, dst);}
		}
	}
	{g_array_free(delp, TRUE); g_array_free(starp, TRUE);}
}
else
{
	str=g_strdup_printf(_(\"Loading failed for file: %s, Error: %s.\"), fin, (gchar*) Err);
	gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
	{g_free(str); g_error_free(Err);}
}
{g_free(contents); g_strfreev(strat2);}"

str3="iv=g_array_index(bsra, gdouble, j);
k=0;
while ((k<lc)&&(iv>g_array_index(xp, gdouble, k))) k++;
sr=k;
iv=g_array_index(bspa, gdouble, j);
while ((k<lc)&&(iv>=g_array_index(xp, gdouble, k))) k++;
sp=k-sr;
if (sp>zp) sp=zp;
iv=(sp-1)/(zp*(g_array_index(xp, gdouble, sp+sr-1)-g_array_index(xp, gdouble, sr)));
g_array_append_val(delp, iv);"

strce="ce=0;
for (j=1; j<=16; j++) ce+=g_array_index(yp, gdouble, lc-j);
ce/=16;"

stro_t="iv=g_array_index(bsra, gdouble, j);
k=0;
while ((k<lc)&&(iv>g_array_index(xp, gdouble, k))) k++;
sr=k;
iv=g_array_index(bspa, gdouble, j);
while ((k<lc)&&(iv>=g_array_index(xp, gdouble, k))) k++;
sp=k-sr;
if (sp>zp)
{
	sp=zp;
	{ofs=g_array_index(yp, gdouble, sr); ofe=g_array_index(yp, gdouble, sp+sr-1); k=1;}
	while (k<8) {ofs+=g_array_index(yp, gdouble, sr+k); ofe+=g_array_index(yp, gdouble, sp+sr-(++k));}
	{ofs/=8; ofe/=8;}
}
else if (sp<16) {ofs=g_array_index(yp, gdouble, sr); ofe=g_array_index(yp, gdouble, sp+sr-1);}
else
{
	{ofs=g_array_index(yp, gdouble, sr); ofe=g_array_index(yp, gdouble, sp+sr-1); k=1;}
	while (k<8) {ofs+=g_array_index(yp, gdouble, sr+k); ofe+=g_array_index(yp, gdouble, sp+sr-(++k));}
	{ofs/=8; ofe/=8;}
}
iv=(sp-1)/(zp*(g_array_index(xp, gdouble, sp+sr-1)-g_array_index(xp, gdouble, sr)));
g_array_append_val(delp, iv);"

strerr="if ((ofs<DZE)&&(ofs>NZE))
{
	str=g_strdup(_(\"Offset must be nonzero for linear measurements.\"));
	gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
	g_free(str);
}"

str_ntds="for (k=0; k<sp; k++)
{
	clc=ofs-g_array_index(yp, gdouble, k+sr);
	if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_ntdsh="for (k=0; k<sp; k++)
{
	clc=ofs+ce-g_array_index(yp, gdouble, k+sr);
	if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_ntdsw="for (k=0; k<sp; k++)
{
	clc=ofs+(k*(ofe-ofs)/(sp-1))-g_array_index(yp, gdouble, k+sr);
	if (clc<NZE) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_ptds="for (k=0; k<sp; k++)
{
	clc=g_array_index(yp, gdouble, k+sr)-ofs;
	if (clc<NZE) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"


str_ptdsh="for (k=0; k<sp; k++)
	{
	clc=g_array_index(yp, gdouble, k+sr)-ofs-ce;
	if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_ptdsw="for (k=0; k<sp; k++)
{
	clc=g_array_index(yp, gdouble, k+sr)-ofs-(k*(ofe-ofs)/(sp-1));
	if (clc<NZE) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_nrds="for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(ofs-g_array_index(yp, gdouble, k+sr));"

str_nrdsh="for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(ofs+ce-g_array_index(yp, gdouble, k+sr));"

str_prds="for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(g_array_index(yp, gdouble, k+sr)-ofs);"

str_prdsh="for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(g_array_index(yp, gdouble, k+sr)-ofs-ce);"

str_tls="for (k=0; k<sp; k++)
{
	clc=1-(g_array_index(yp, gdouble, k+sr)/ofs);
	if (clc>DZE) yt[k+(j*zp)]=log(clc);
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_tlsh="for (k=0; k<sp; k++)
{
	clc=1-(g_array_index(yp, gdouble, k+sr)/(ofs+ce));
	if (clc>0) yt[k+(j*zp)]=log(clc);
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_tlsw="for (k=0; k<sp; k++)
{
	clc=ofs+(k*(ofe-ofs)/(sp-1));
	if (clc<DZE && clc>NZE) yt[k+(j*zp)]=-G_MAXDOUBLE;
	else
	{
		clc=1-(g_array_index(yp, gdouble, k+sr)/clc);
		if (clc>DZE) yt[k+(j*zp)]=log(clc);
		else yt[k+(j*zp)]=-G_MAXDOUBLE;
	}
}"

str_rls="for (k=0; k<sp; k++)
{
	clc=g_array_index(yp, gdouble, k+sr)/ofs;
	if (clc>DZE) yt[k+(j*zp)]=log(clc);
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_rlsh="for (k=0; k<sp; k++)
{
	clc=g_array_index(yp, gdouble, k+sr)/(ofs+ce);
	if (clc>0) yt[k+(j*zp)]=log(clc);
	else yt[k+(j*zp)]=-G_MAXDOUBLE;
}"

str_ntd0="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(ofs-g_array_index(yp, gdouble, k+sr)));"

str_ntd0h="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(ofs+ce-g_array_index(yp, gdouble, k+sr)));"

str_ntd0w="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(ofs+(k*(ofe-ofs)/(sp-1))-g_array_index(yp, gdouble, k+sr)));"

str_ptd0w="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(g_array_index(yp, gdouble, k+sr)-ofs));"

str_ptd0h="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(g_array_index(yp, gdouble, k+sr)-ofs-ce));"

str_ptd0w="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(g_array_index(yp, gdouble, k+sr)-ofs-(k*(ofe-ofs)/(sp-1))));"

str_nrd0="for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(ofs-g_array_index(yp, gdouble, k+sr)));"

str_nrd0h="for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(ofs+ce-g_array_index(yp, gdouble, k+sr)));"

str_prd0="for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(g_array_index(yp, gdouble, k+sr)-ofs));"

str_prd0h="for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(g_array_index(yp, gdouble, k+sr)-ofs-ce));"

str_tl0="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-(g_array_index(yp, gdouble, k+sr)/ofs);"

str_tl0h="for (k=0; k<sp; k++) yt[k+(j*zp)]=1-(g_array_index(yp, gdouble, k+sr)/(ofs+ce));"

str_tl0w="for (k=0; k<sp; k++)
{
	clc=ofs+(k*(ofe-ofs)/(sp-1));
	if (clc<DZE && clc>NZE) yt[k+(j*zp)]=-G_MAXDOUBLE;
	else yt[k+(j*zp)]=1-(g_array_index(yp, gdouble, k+sr)/clc);
}"

str_rl0="for (k=0; k<sp; k++) yt[k+(j*zp)]=g_array_index(yp, gdouble, k+sr)/ofs;"

str_rl0h="for (k=0; k<sp; k++) yt[k+(j*zp)]=g_array_index(yp, gdouble, k+sr)/(ofs+ce);"

{
echo "/***************************************************************************"
echo " *            batc.c"
echo " *"
echo " *  Sat Dec  4 17:18:14 2010"
echo " *  Copyright  2010  Paul Childs"
echo " *  <pchilds@physics.org>"
echo " ****************************************************************************/"
echo ""
echo "/*"
echo " * This program is free software; you can redistribute it and/or modify"
echo " * it under the terms of the GNU General Public License as published by"
echo " * the Free Software Foundation; either version 2 of the License, or"
echo " * (at your option) any later version."
echo " *"
echo " * This program is distributed in the hope that it will be useful,"
echo " * but WITHOUT ANY WARRANTY; without even the implied warranty of"
echo " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
echo " * GNU Library General Public License for more details."
echo " *"
echo " * You should have received a copy of the GNU General Public License"
echo " * along with this program; if not, write to the Free Software"
echo " * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA"
echo " */"
echo ""
echo "#include \"batc.h\""
echo "GtkWidget *adb, *cft, *dialog, *lbl1, *lbl2, *spin;"
echo "GList *conff=NULL, *confv=NULL;"
echo "GSList *confb=NULL;"
echo ""
echo "void tsw(GtkWidget* widget, gpointer dta)"
echo "{"
echo "	gchar *s1=NULL, *s2=NULL;"
echo "	gdouble val, val2;"
echo "	GList *iter=NULL;"
echo "	guint ps;"
echo ""
echo "	ps=GPOINTER_TO_INT(dta);"
echo "	iter=g_list_nth(conff, ps);"
echo "	s2=g_strdup(gtk_label_get_label(GTK_LABEL(iter->data)));"
echo "	iter=(iter->prev);"
echo "	s1=g_strdup(gtk_label_get_label(GTK_LABEL(iter->data)));"
echo "	gtk_label_set_label(GTK_LABEL(iter->data), s2);"
echo "	iter=(iter->next);"
echo "	gtk_label_set_label(GTK_LABEL(iter->data), s1);"
echo "	{g_free(s1); g_free(s2);}"
echo "	iter=g_list_nth(confv, ps);"
echo "	val2=gtk_spin_button_get_value(GTK_SPIN_BUTTON(iter->data));"
echo "	iter=(iter->prev);"
echo "	val=gtk_spin_button_get_value(GTK_SPIN_BUTTON(iter->data));"
echo "	gtk_spin_button_set_value(GTK_SPIN_BUTTON(iter->data), val2);"
echo "	iter=(iter->next);"
echo "	gtk_spin_button_set_value(GTK_SPIN_BUTTON(iter->data), val);"
echo "}"
echo ""
echo "void tdl(GtkWidget* widget, gpointer dta)"
echo "{"
echo "	GList *iter1=NULL, *iter2=NULL;"
echo "	gchar *s=NULL;"
echo "	gdouble val;"
echo "	guint ps;"
echo "	gint rw;"
echo ""
echo "	g_object_get(G_OBJECT(cft), \"n-rows\", &rw, NULL);"
echo "	rw-=3;"
echo "	if (rw<=2)"
echo "	{"
echo "		gtk_container_remove(GTK_CONTAINER(cft), widget);"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(conff->data));"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(confv->data));"
echo "		{g_slist_free(confb); g_list_free(conff); g_list_free(confv);}"
echo "		{confb=NULL; conff=NULL; confv=NULL;}"
echo "	}"
echo "	else"
echo "	{"
echo "		ps=GPOINTER_TO_INT(dta);"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(confb->data));"
echo "		confb=(confb->next);"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(confb->data));"
echo "		confb=(confb->next);"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(confb->data));"
echo "		confb=(confb->next);"
echo "		{iter1=(g_list_nth(conff, ps))->next; iter2=(g_list_nth(confv, ps))->next;}"
echo "		while (iter1)"
echo "		{"
echo "			s=g_strdup(gtk_label_get_label(GTK_LABEL(iter1->data)));"
echo "			gtk_label_set_label(GTK_LABEL((iter1->prev)->data), s);"
echo "			val=gtk_spin_button_get_value(GTK_SPIN_BUTTON(iter2->data));"
echo "			gtk_spin_button_set_value(GTK_SPIN_BUTTON((iter2->prev)->data), val);"
echo "			{g_free(s); iter1=(iter1->next); iter2=(iter2->next);}"
echo "		}"
echo "		iter1=g_list_last(conff);"
echo "		iter2=(iter1->prev);"
echo "		{(iter2->next)=NULL; (iter1->prev)=NULL;}"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(iter1->data));"
echo "		iter1=g_list_last(confv);"
echo "		iter2=(iter1->prev);"
echo "		{(iter2->next)=NULL; (iter1->prev)=NULL;}"
echo "		gtk_container_remove(GTK_CONTAINER(cft), GTK_WIDGET(iter1->data));"
echo "	}"
echo "	g_object_ref(G_OBJECT(adb));"
echo "	gtk_container_remove(GTK_CONTAINER(cft), adb);"
echo "	gtk_table_attach(GTK_TABLE(cft), adb, 1, 2, rw-1, rw, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "	{g_object_unref(G_OBJECT(adb)); g_object_ref(G_OBJECT(spin));}"
echo "	gtk_container_remove(GTK_CONTAINER(cft), spin);"
echo "	gtk_table_attach(GTK_TABLE(cft), spin, 2, 3, rw-1, rw, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "	g_object_unref(G_OBJECT(spin));"
echo "	gtk_table_resize(GTK_TABLE(cft), rw, 3);"
echo "}"
echo ""
echo "void upt(GtkWidget* widget, gpointer dta)"
echo "{"
echo "	AtkObject *atk_lbl, *atk_ll, *atk_wgt;"
echo "	gdouble val;"
echo "	gint rw, j;"
echo "	gint ps;"
echo "	GSList *fls=NULL;"
echo "	GtkAdjustment *adj;"
echo "	GtkWidget *btd, *btt, *btu, *lbl, *wwfile;"
echo ""
echo "	wwfile=gtk_file_chooser_dialog_new(_(\"Select Data File(s)\"), GTK_WINDOW(dialog), GTK_FILE_CHOOSER_ACTION_OPEN, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL);"
echo "	gtk_file_chooser_set_select_multiple(GTK_FILE_CHOOSER(wwfile), TRUE);"
echo "	gtk_file_chooser_set_show_hidden(GTK_FILE_CHOOSER(wwfile), FALSE);"
echo "	gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(wwfile), fold);"
echo "	g_signal_connect(G_OBJECT(wwfile), \"destroy\", G_CALLBACK(gtk_widget_destroy), G_OBJECT(wwfile));"
echo "	if (gtk_dialog_run(GTK_DIALOG(wwfile))==GTK_RESPONSE_ACCEPT)"
echo "	{"
echo "		g_object_get(G_OBJECT(cft), \"n-rows\", &rw, NULL);"
echo "		ps=(rw-2)/3;"
echo "		fls=gtk_file_chooser_get_filenames(GTK_FILE_CHOOSER(wwfile));"
echo "		j=g_slist_length(fls);"
echo "		gtk_table_resize(GTK_TABLE(cft), rw+(3*j), 3);"
echo "		val=gtk_spin_button_get_value(GTK_SPIN_BUTTON(spin));"
echo "		g_object_ref(G_OBJECT(widget));"
echo "		gtk_container_remove(GTK_CONTAINER(cft), widget);"
echo "		atk_lbl=gtk_widget_get_accessible(GTK_WIDGET(lbl2));"
echo "		if (ps==0)"
echo "		{"
echo "			lbl=gtk_label_new(g_strdup((gchar*) (fls->data)));"
echo "			gtk_table_attach(GTK_TABLE(cft), lbl, 1, 2, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(lbl);"
echo "			conff=g_list_append(conff, (gpointer) lbl);"
echo "			g_free(fls->data);"
echo "			fls=(fls->next);"
echo "			btt=gtk_button_new_from_stock(GTK_STOCK_DELETE);"
echo "			g_signal_connect(G_OBJECT(btt), \"clicked\", G_CALLBACK(tdl), GINT_TO_POINTER(ps));"
echo "			gtk_table_attach(GTK_TABLE(cft), btt, 0, 1, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(btt);"
echo "			confb=g_slist_prepend(confb, (gpointer) btt);"
echo "			atk_wgt=gtk_widget_get_accessible(lbl1);"
echo "			atk_ll=gtk_widget_get_accessible(GTK_WIDGET(lbl));"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABEL_FOR, atk_ll);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_LABELLED_BY, atk_wgt);"
echo "			atk_wgt=gtk_widget_get_accessible(spin);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_LABEL_FOR, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABELLED_BY, atk_ll);"
echo "			confv=g_list_append(confv, (gpointer) spin);"
echo "			{ps++; rw+=3;}"
echo "			adj=(GtkAdjustment*) gtk_adjustment_new(val, -G_MAXDOUBLE, G_MAXDOUBLE, 1.0, 5.0, 0.0);"
echo "			spin=gtk_spin_button_new(adj, 0, 0);"
echo "			gtk_widget_show(spin);"
echo "			gtk_table_attach(GTK_TABLE(cft), spin, 2, 3, 4, 5, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			atk_wgt=gtk_widget_get_accessible(spin);"
echo "			atk_object_add_relationship(atk_lbl, ATK_RELATION_LABEL_FOR, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABELLED_BY, atk_lbl);"
echo "		}"
echo "		else atk_ll=gtk_widget_get_accessible(GTK_WIDGET(g_list_last(conff)->data));"
echo "		while (fls)"
echo "		{"
echo "			btd=gtk_button_new_from_stock(GTK_STOCK_GO_DOWN);"
echo "			g_signal_connect(G_OBJECT(btd), \"clicked\", G_CALLBACK(tsw), GINT_TO_POINTER(ps));"
echo "			gtk_table_attach(GTK_TABLE(cft), btd, 0, 1, rw-3, rw-2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(btd);"
echo "			confb=g_slist_prepend(confb, (gpointer) btd);"
echo "			btu=gtk_button_new_from_stock(GTK_STOCK_GO_UP);"
echo "			g_signal_connect(G_OBJECT(btu), \"clicked\", G_CALLBACK(tsw), GINT_TO_POINTER(ps));"
echo "			gtk_table_attach(GTK_TABLE(cft), btu, 0, 1, rw-2, rw-1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(btu);"
echo "			confb=g_slist_prepend(confb, (gpointer) btu);"
echo "			atk_wgt=gtk_widget_get_accessible(btd);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_CONTROLLED_BY, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_CONTROLLER_FOR, atk_ll);"
echo "			atk_wgt=gtk_widget_get_accessible(btu);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_CONTROLLED_BY, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_CONTROLLER_FOR, atk_ll);"
echo "			lbl=gtk_label_new(g_strdup((gchar*) (fls->data)));"
echo "			gtk_table_attach(GTK_TABLE(cft), lbl, 1, 2, rw-1, rw, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(lbl);"
echo "			conff=g_list_append(conff, (gpointer) lbl);"
echo "			g_free(fls->data);"
echo "			fls=(fls->next);"
echo "			atk_wgt=gtk_widget_get_accessible(lbl1);"
echo "			atk_ll=gtk_widget_get_accessible(GTK_WIDGET(lbl));"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABEL_FOR, atk_ll);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_LABELLED_BY, atk_wgt);"
echo "			atk_wgt=gtk_widget_get_accessible(btd);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_CONTROLLED_BY, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_CONTROLLER_FOR, atk_ll);"
echo "			atk_wgt=gtk_widget_get_accessible(btu);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_CONTROLLED_BY, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_CONTROLLER_FOR, atk_ll);"
echo "			btt=gtk_button_new_from_stock(GTK_STOCK_DELETE);"
echo "			g_signal_connect(G_OBJECT(btt), \"clicked\", G_CALLBACK(tdl), GINT_TO_POINTER(ps));"
echo "			gtk_table_attach(GTK_TABLE(cft), btt, 0, 1, rw-1, rw, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(btt);"
echo "			confb=g_slist_prepend(confb, (gpointer) btt);"
echo "			atk_wgt=gtk_widget_get_accessible(btt);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_CONTROLLED_BY, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_CONTROLLER_FOR, atk_ll);"
echo "			atk_wgt=gtk_widget_get_accessible(spin);"
echo "			atk_object_add_relationship(atk_ll, ATK_RELATION_LABEL_FOR, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABELLED_BY, atk_ll);"
echo "			confv=g_list_append(confv, (gpointer) spin);"
echo "			{ps++; rw+=3;}"
echo "			adj=(GtkAdjustment*) gtk_adjustment_new(val, -G_MAXDOUBLE, G_MAXDOUBLE, 1.0, 5.0, 0.0);"
echo "			spin=gtk_spin_button_new(adj, 0, 0);"
echo "			gtk_widget_show(spin);"
echo "			gtk_table_attach(GTK_TABLE(cft), spin, 2, 3, rw-1, rw, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			atk_wgt=gtk_widget_get_accessible(spin);"
echo "			atk_object_add_relationship(atk_lbl, ATK_RELATION_LABEL_FOR, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABELLED_BY, atk_lbl);"
echo "		}"
echo "		gtk_table_attach(GTK_TABLE(cft), widget, 1, 2, rw-1, rw, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "		g_object_unref(G_OBJECT(widget));"
echo "	}"
echo "	gtk_widget_destroy(wwfile);"
echo "}"
echo ""
echo ""
echo "void bat(GtkWidget *widget, gpointer data)"
echo "{"
echo "	AtkObject *atk_lbl, *atk_wgt;"
echo "	double *yt, *star;"
echo "	fftw_plan p;"
echo "	fftw_r2r_kind type=FFTW_R2HC;"
echo "	GArray *delp, *starp, *nx, *st, *sz, *x, *xp, *y, *yp;"
echo "	gchar *contents, *contents2, *dm, *fin=NULL, *str, *s2;"
echo "	gchar **strary, **strary2, **strat, **strat2;"
echo "	gchar s1[10];"
echo "	gdouble ce, clc, cn, ct, ddp, dst, idelf, iv, ivd, ivdt, lcl, mny, mxy, ofe, ofs, phi, phia, phio, pn, tcn, tp, twd, vt, vzt, xi, xf, xx;"
echo "	GError *Err=NULL;"
echo "	gint dr, dx, dx2, j, jdimx, k, kib, l, lc, lcib, m, mx, n, sal, sr, sp, trc, zp;"
echo "	GList *iter1, *iter2;"
echo "	GSList *list;"
echo "	GtkAdjustment *adj, *adj2;"
echo "	GtkPlotLinear *plt;"
echo "	GtkPlotPolar *plt2;"
echo "	GtkWidget *cont, *content, *label, *scroll, *wfile;"
echo ""
echo "	wfile=gtk_file_chooser_dialog_new(_(\"Select Config File\"), GTK_WINDOW(window), GTK_FILE_CHOOSER_ACTION_SAVE, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_NEW, GTK_RESPONSE_APPLY, GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL);"
echo "	gtk_file_chooser_set_select_multiple(GTK_FILE_CHOOSER(wfile), FALSE);"
echo "	gtk_file_chooser_set_show_hidden(GTK_FILE_CHOOSER(wfile), FALSE);"
echo "	gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(wfile), folr);"
echo "	g_signal_connect(G_OBJECT(wfile), \"destroy\", G_CALLBACK(gtk_widget_destroy), G_OBJECT(wfile));"
echo "	dr=gtk_dialog_run(GTK_DIALOG(wfile));"
echo "	if (dr==GTK_RESPONSE_APPLY)"
echo "	{"
echo "		fin=gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(wfile));"
echo "		if (fin)/* also overwrite confirmation? */"
echo "		{"
echo "			dialog=gtk_dialog_new_with_buttons(_(\"Configuration file generation\"), GTK_WINDOW(wfile), GTK_DIALOG_DESTROY_WITH_PARENT, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_SAVE, GTK_RESPONSE_APPLY, NULL);"
echo "			g_signal_connect_swapped(G_OBJECT(dialog), \"destroy\", G_CALLBACK(gtk_widget_destroy), G_OBJECT(dialog));"
echo "			gtk_widget_show(dialog);"
echo "			content=gtk_dialog_get_content_area(GTK_DIALOG(dialog));"
echo "			cft=gtk_table_new(2, 3, FALSE);"
echo "			gtk_widget_show(cft);"
echo "			lbl1=gtk_label_new(_(\"File:\"));"
echo "			gtk_widget_show(lbl1);"
echo "			gtk_table_attach(GTK_TABLE(cft), lbl1, 1, 2, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			lbl2=gtk_label_new(_(\"Measurand\nValue:\"));"
echo "			gtk_widget_show(lbl2);"
echo "			gtk_table_attach(GTK_TABLE(cft), lbl2, 2, 3, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			adb=gtk_button_new_with_label(_(\"Add another file\"));"
echo "			gtk_widget_show(adb);"
echo "			gtk_table_attach(GTK_TABLE(cft), adb, 1, 2, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			g_signal_connect(G_OBJECT(adb), \"clicked\", G_CALLBACK(upt), NULL);"
echo "			adj=(GtkAdjustment*) gtk_adjustment_new(0, -G_MAXDOUBLE, G_MAXDOUBLE, 1.0, 5.0, 0.0);"
echo "			spin=gtk_spin_button_new(adj, 0, 0);"
echo "			gtk_widget_show(spin);"
echo "			gtk_table_attach(GTK_TABLE(cft), spin, 2, 3, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			atk_wgt=gtk_widget_get_accessible(spin);"
echo "			atk_lbl=gtk_widget_get_accessible(GTK_WIDGET(lbl2));"
echo "			atk_object_add_relationship(atk_lbl, ATK_RELATION_LABEL_FOR, atk_wgt);"
echo "			atk_object_add_relationship(atk_wgt, ATK_RELATION_LABELLED_BY, atk_lbl);"
echo "			adj=(GtkAdjustment*) gtk_adjustment_new(0, 0, 0, 0.0, 0.0, 0.0);"
echo "			adj2=(GtkAdjustment*) gtk_adjustment_new(0, -G_MAXDOUBLE, G_MAXDOUBLE, 1.0, 5.0, 0.0);"
echo "			scroll=gtk_scrolled_window_new(adj, adj2);"
echo "			gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);"
echo "			gtk_scrolled_window_add_with_viewport(GTK_SCROLLED_WINDOW(scroll), cft);"
echo "			gtk_widget_show(scroll);"
echo "			gtk_box_pack_start(GTK_BOX(content), scroll, TRUE, TRUE, 2);"
echo "			if (gtk_dialog_run(GTK_DIALOG(dialog))==GTK_RESPONSE_APPLY)"
echo "			{"
echo "				mx=0;"
echo "				{iter1=g_list_first(conff); iter2=g_list_first(confv);}"
echo "				if (iter1)"
echo "				{"
echo "					s2=g_strdup(gtk_label_get_label(GTK_LABEL(iter1->data)));"
echo "					iv=gtk_spin_button_get_value(GTK_SPIN_BUTTON(iter2->data));"
echo "					{iter1=(iter1->next); iter2=(iter2->next);}"
echo "					g_snprintf(s1, 10, \"%f\", iv);"
echo "					contents2=g_strjoin(\"\\t\", s1, s2, NULL);"
echo "					g_free(s2);"
echo "					mx++;"
echo "					while (iter1)"
echo "					{"
echo "						s2=g_strdup(gtk_label_get_label(GTK_LABEL(iter1->data)));"
echo "						iter1=(iter1->next);"
echo "						iv=gtk_spin_button_get_value(GTK_SPIN_BUTTON(iter2->data));"
echo "						iter2=(iter2->next);"
echo "						g_snprintf(s1, 10, \"%f\", iv);"
echo "						str=g_strjoin(\"\\t\", s1, s2, NULL);"
echo "						contents=g_strdup(contents2);"
echo "						{g_free(s2); g_free(contents2);}"
echo "						contents2=g_strjoin(DLMT, contents, str, NULL);"
echo "						{g_free(contents); g_free(str);}"
echo "						mx++;"
echo "					}"
echo "					g_file_set_contents(fin, contents2, -1, &Err);"
echo "					g_free(contents2);"
echo "					if (Err)"
echo "					{"
echo "						str=g_strdup_printf(_(\"Error Saving file: %s.\"), (Err->message));"
echo "						gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);"
echo "						{g_free(str); g_error_free(Err);}"
echo "					}"
echo "					else dr=GTK_RESPONSE_ACCEPT;"
echo "				}"
echo "				else"
echo "				{"
echo "					str=g_strdup(_(\"No filenames given.\"));"
echo "					gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);"
echo "					g_free(str);"
echo "				}"
echo "			}"
echo "			{g_list_free(conff); g_list_free(confv); g_slist_free(confb); gtk_widget_destroy(dialog);}"
echo "		}"
echo "		g_free(fin);"
echo "	}"
echo "	if (dr!=GTK_RESPONSE_ACCEPT) gtk_widget_destroy(wfile);"
echo "	else"
echo "	{"
echo "		g_free(folr);"
echo "		folr=gtk_file_chooser_get_current_folder(GTK_FILE_CHOOSER(wfile));"
echo "		fin=gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(wfile));"
echo "		gtk_widget_destroy(wfile);"
echo "		if (g_file_get_contents(fin, &contents2, NULL, &Err))"
echo "		{"
echo "			{g_array_free(vis, FALSE); g_array_free(doms, FALSE); g_array_free(chp, FALSE);}"
echo "			strary2=g_strsplit_set(contents2, DLMT, 0);"
echo "			mx=g_strv_length(strary2);"
echo "			zp=1<<(gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(zpd)));"
echo "			jdimx=(bsra->len);"
echo "			n=zp*jdimx;"
echo "			kdimxf=(isra->len)/kdimxf;"
echo "			yt=fftw_malloc(sizeof(double)*n);"
echo "			star=fftw_malloc(sizeof(double)*n);"
echo "			p=fftw_plan_many_r2r(1, &zp, jdimx, yt, NULL, 1, zp, star, NULL, 1, zp, &type, FFTW_ESTIMATE);"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(anosa))) {kib=2; lcib=-1; dm=\",\";}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(sws))) {kib=0; lcib=-1; dm=\"\\t\";}"
echo "			else {kib=0; lcib=0; dm=\"\\t\";}"
echo "			trc=g_array_index(GTK_PLOT(plot1)->stride, gint, 0)-1;"
echo "			list=group2;"
echo "			while (list)"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(list->data))) break;"
echo "				{list=(list->next); trc--;}"
echo "			}"
echo "			vis=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx*kdimxf*mx);"
echo "			doms=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx*kdimxf*mx);"
echo "			chp=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx*kdimxf*mx);"
echo "			strat2=g_strsplit_set(strary2[0], \"\\t\", 0);"
echo "			xi=g_ascii_strtod(g_strstrip(strat2[0]), NULL);"
echo "			xf=xi;"
echo "			flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_POL|PROC_COM|PROC_RI);"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(wll)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(chi)))"
echo "				{"
echo "					flags|=PROC_CHP;"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 3*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 3*mx*jdimx*kdimxf);"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "								{"
echo "									if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssw-c */"
echo "									{"
echo "										for (m=0; m<mx; m++)"
echo "										{"
echo "${str0}"
echo "												for (j=0; j<jdimx; j++)"
echo "												{"
echo "												}"
echo "${str1}"
echo "										}"
echo "									}"
echo "									else /* +TdBssw-c */"
echo "									{"
echo "										for (m=0; m<mx; m++)"
echo "										{"
echo "${str0}"
echo "												for (j=0; j<jdimx; j++)"
echo "												{"
echo "												}"
echo "${str1}"
echo "										}"
echo "									}"
echo "								}"
echo "								else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssw-c */"
echo "								{"
echo "									ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +RdBssw-c */"
echo "								{"
echo "									ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssw-c +Tlssw-c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* -Rlssw-c +Rlssw-c */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0w-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +TdB0w-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0w-c */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +RdB0w-c */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0w-c +Tl0w-c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* -Rl0w-c +Rl0w-c */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssw+c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "${stro_t}"
echo "${str_ntdsw}"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +TdBssw+c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "${stro_t}"
echo "${str_ptdsw}"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssw+c */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_nrds}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +RdBssw+c */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_prds}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssw+c +Tlssw+c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${stro_t}"
echo "${str_tlsw}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* -Rlssw+c +Rlssw+c */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_rls}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0w+c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${stro_t}"
echo "${str_ntd0w}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +TdB0w+c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${stro_t}"
echo "${str_ptd0w}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0w+c */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_nrd0}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* +RdB0w+c */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_prd0}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0w+c +Tl0w+c */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${stro_t}"
echo "${str_tl0w}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "					else /* -Rl0w+c +Rl0w+c */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_rl0};"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssw- */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str2}"
echo "									}"
echo "								}"
echo "								else /* +TdBssw- */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str2}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssw- */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +RdBssw- */"
echo "							{"
echo "								ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssw- +Tlssw- */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* -Rlssw- +Rlssw- */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0w- */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +TdB0w- */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0w- */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +RdB0w- */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0w- +Tl0w- */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* -Rl0w- +Rl0w- */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssw+ */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${stro_t}"
echo "${str_ntdsw}"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +TdBssw+ */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${stro_t}"
echo "											for (k=0; k<sp; k++)"
echo "											{"
echo "${str_ptdsw}"
echo "											}"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssw+ */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_nrds}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +RdBssw+ */"
echo "						{"
echo "							ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_prds}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssw+ +Tlssw+ */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${stro_t}"
echo "${str_tlsw}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* -Rlssw+ +Rlssw+ */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_rls}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0w+ */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${stro_t}"
echo "${str_ntd0w}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +TdB0w+ */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${stro_t}"
echo "${str_ptd0w}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0w+ */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_nrd0}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* +RdB0w+ */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_prd0}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0w+ +Tl0w+ */"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					for (m=0; m<mx; m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${stro_t}"
echo "${str_tl0w}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "				else /* -Rl0w+ +Rl0w+ */"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "					for (m=0; m<mx; m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_rl0}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(oft)))"
echo "			{"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst))-oe;"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(chi)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 3*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 3*mx*jdimx*kdimxf);"
echo "					flags|=(PROC_OFT|PROC_CHP);"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "								{"
echo "									if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssh-c */"
echo "									{"
echo "										for (m=0; m<mx; m++)"
echo "										{"
echo "${str0}"
echo "${strce}"
echo "												for (j=0; j<jdimx; j++)"
echo "												{"
echo "												}"
echo "${str1}"
echo "										}"
echo "									}"
echo "									else /* +TdBssh-c */"
echo "									{"
echo "										for (m=0; m<mx; m++)"
echo "										{"
echo "${str0}"
echo "${strce}"
echo "												for (j=0; j<jdimx; j++)"
echo "												{"
echo "												}"
echo "${str1}"
echo "										}"
echo "									}"
echo "								}"
echo "								else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBss-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +RdBssh-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssh-c +Tlssh-c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* -Rlssh-c +Rlssh-c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +TdB0h-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0h-c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +RdB0h-c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0h-c +Tl0h-c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* -Rl0h-c +Rl0h-c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssh+c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "${str3}"
echo "${str_ntdsh}"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +TdBssh+c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "${str3}"
echo "${str_ptdsh}"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssh+c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_nrdsh}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +RdBssh+c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_prdsh}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssh+c +Tlssh+c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_tlsh}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* -Rlssh+c +Rlssh+c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_rlsh}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0h+c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_ntd0h}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +TdB0h+c */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_ptd0h}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0h+c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_nrd0h}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* +RdB0h+c */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_prd0h}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0h+c +Tl0h+c */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_tl0h}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "					else /* -Rl0h+c +Rl0h+c */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_rl0h}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					flags|=PROC_OFT;"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssh- */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str2}"
echo "									}"
echo "								}"
echo "								else /* +TdBssh- */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "${strce}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str2}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssh- */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +RdBssh- */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssh- +Tlssh- */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* -Rlssh- +Rlssh- */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0h- */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +TdB0h- */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0h- */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +RdB0h- */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0h- +Tl0h- */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* -Rl0h- +Rl0h- */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					flags|=PROC_OFT;"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssh+ */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_ntdsh}"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +TdBssh+ */"
echo "							{"
echo "								for (m=0; m<mx; m++)"
echo "								{"
echo "${str0}"
echo "${strce}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_ptdsh}"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssh+ */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_nrdsh}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +RdBssh+ */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_prdsh}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssh+ +Tlssh+ */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_tlsh}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* -Rlssh+ +Rlssh+ */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_rlsh}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					flags|=PROC_OFT;"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0h+ */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_ntd0h}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +TdB0h+ */"
echo "						{"
echo "							for (m=0; m<mx; m++)"
echo "							{"
echo "${str0}"
echo "${strce}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_ptd0h}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0h+ */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_nrd0h}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* +RdB0h+ */"
echo "					{"
echo "						for (m=0; m<mx; m++)"
echo "						{"
echo "${str0}"
echo "${strce}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_prd0h}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0h+ +Tl0h+ */"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					flags|=PROC_OFT;"
echo "					for (m=0; m<mx; m++)"
echo "					{"
echo "${str0}"
echo "${strce}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_tl0h}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "				else /* -Rl0h+ +Rl0h+ */"
echo "				{"
echo "					x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "					flags|=PROC_OFT;"
echo "					for (m=0; m<mx; m++)"
echo "					{"
echo "${str0}"
echo "${strce}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_rl0h}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "				{oe=ce; ofs+=ce;}"
echo "				gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), ofs);"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(chi)))"
echo "			{"
echo "				x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 3*mx*jdimx*kdimxf);"
echo "				y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 3*mx*jdimx*kdimxf);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				flags|=PROC_CHP;"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "							{"
echo "								if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBsso-c */"
echo "								{"
echo "									for (m=0; m<mx; m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "								else /* +TdBsso-c */"
echo "								{"
echo "									for (m=0; m<g_strv_length(strary2); m++)"
echo "									{"
echo "${str0}"
echo "											for (j=0; j<jdimx; j++)"
echo "											{"
echo "											}"
echo "${str1}"
echo "									}"
echo "								}"
echo "							}"
echo "							else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBsso-c */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +RdBsso-c */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlsso-c +Tlsso-c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* -Rlsso-c +Rlsso-c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0o-c */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +TdB0o-c */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0o-c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* +RdB0o-c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0o-c +Tl0o-c */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "					else /* -Rl0o-c +Rl0o-c */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBsso+c */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_ntds}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "							else /* +TdBsso+c */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "${str3}"
echo "${str_ptds}"
echo "										}"
echo "${str1}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBsso+c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_nrds}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* +RdBsso+c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_prds}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlsso+c +Tlsso+c */"
echo "					{"
echo "${strerr}"
echo "						else"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_tls}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else /* -Rlsso+c +Rlsso+c */"
echo "					{"
echo "${strerr}"
echo "						else"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_rls}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0o+c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_ntd0}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "						else /* +TdB0o+c */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_ptd0}"
echo "									}"
echo "${str1}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0o+c */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_nrd0}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "					else /* +RdB0o+c */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_prd0}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0o+c +Tl0o+c */"
echo "				{"
echo "${strerr}"
echo "					else"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_tl0}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "				else /* -Rl0o+c +Rl0o+c */"
echo "				{"
echo "${strerr}"
echo "					else"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_rl0}"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))"
echo "			{"
echo "				x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBsso- */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "							else /* +TdBsso- */"
echo "							{"
echo "								for (m=0; m<g_strv_length(strary2); m++)"
echo "								{"
echo "${str0}"
echo "										for (j=0; j<jdimx; j++)"
echo "										{"
echo "										}"
echo "${str2}"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBsso- */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +RdBsso- */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlsso- +Tlsso- */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* -Rlsso- +Rlsso- */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0o- */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +TdB0o- */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0o- */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* +RdB0o- */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "								}"
echo "${str1}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0o- +Tl0o- */"
echo "				{"
echo "					for (m=0; m<g_strv_length(strary2); m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "				else /* -Rl0o- +Rl0o- */"
echo "				{"
echo "					for (m=0; m<g_strv_length(strary2); m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "			{"
echo "				x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBsso+ */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_ntds}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "						else /* +TdBsso+ */"
echo "						{"
echo "							for (m=0; m<g_strv_length(strary2); m++)"
echo "							{"
echo "${str0}"
echo "									for (j=0; j<jdimx; j++)"
echo "									{"
echo "${str3}"
echo "${str_ptds}"
echo "									}"
echo "${str2}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBsso+ */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_nrds}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* +RdBsso+ */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_prds}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlsso+ +Tlsso+ */"
echo "				{"
echo "${strerr}"
echo "					else"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_tls}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else /* -Rlsso+ +Rlsso+ */"
echo "				{"
echo "${strerr}"
echo "					else"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_rls}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "			{"
echo "				x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0o+ */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_ntd0}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "					else /* +TdB0o+ */"
echo "					{"
echo "						for (m=0; m<g_strv_length(strary2); m++)"
echo "						{"
echo "${str0}"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str3}"
echo "${str_ptd0}"
echo "								}"
echo "${str2}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0o+ */"
echo "				{"
echo "					for (m=0; m<g_strv_length(strary2); m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_nrd0}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "				else /* +RdB0o+ */"
echo "				{"
echo "					for (m=0; m<g_strv_length(strary2); m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_prd0}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0o+ +Tl0o+ */"
echo "			{"
echo "				x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "${strerr}"
echo "				else"
echo "				{"
echo "					for (m=0; m<g_strv_length(strary2); m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_tl0}"
echo "							}"
echo "${str2}"
echo "					}"
echo "				}"
echo "			}"
echo "			else /* -Rl0o+ +Rl0o+ */"
echo "			{"
echo "				x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), 2*mx*jdimx*kdimxf);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "${strerr}"
echo "				else"
echo "				{"
echo "					for (m=0; m<g_strv_length(strary2); m++)"
echo "					{"
echo "${str0}"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str3}"
echo "${str_rl0}"
echo "							}"
echo "${str1}"
echo "					}"
echo "				}"
echo "			}"
echo "			{g_strfreev(strary2); fftw_destroy_plan(p); fftw_free(yt); fftw_free(star);}"
echo "			for (j=0; j<jdimx*kdimxf; j++)"
echo "			{"
echo "				iv=g_array_index(vis, gdouble, j);"
echo "				g_array_append_val(y, iv);"
echo "			}"
echo "			for (j=0; j<jdimx*kdimxf; j++)"
echo "			{"
echo "				iv=g_array_index(x, gdouble, j);"
echo "				g_array_append_val(x, iv);"
echo "				iv=g_array_index(doms, gdouble, j);"
echo "				g_array_append_val(y, iv);"
echo "			}"
echo "			if (flags&PROC_CHP)"
echo "			{"
echo "				for (j=0; j<jdimx*kdimxf; j++)"
echo "				{"
echo "					iv=g_array_index(x, gdouble, j);"
echo "					g_array_append_val(x, iv);"
echo "					iv=g_array_index(chp, gdouble, j);"
echo "					g_array_append_val(y, iv);"
echo "				}"
echo "			}"
echo "			dx=jdimx*kdimxf;"
echo "			if ((flagd&DISP_CHP)==0)"
echo "			{"
echo "				if ((flagd&DISP_DMS)==0) dx2=0;"
echo "				else dx2=mx*dx;"
echo "			}"
echo "			else dx2=2*mx*dx;"
echo "			if ((flagd&DISP_MRJ)==0)"
echo "			{"
echo "				if ((flagd&DISP_MRK)==0)/* single plot mode */"
echo "				{"
echo "					{nx=g_array_sized_new(FALSE, FALSE, sizeof(gint), 1); sz=g_array_sized_new(FALSE, FALSE, sizeof(gint), 1); st=g_array_sized_new(FALSE, FALSE, sizeof(gint), 1);}"
echo "					dx2+=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(kind))+(gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jind2))*kdimxf);"
echo "					{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, dx2);}"
echo "					mny=g_array_index(y, gdouble, dx2);"
echo "					{mxy=mny; l=1;}"
echo "					while (l<mx)"
echo "					{"
echo "						xx=g_array_index(y, gdouble, dx2+((l++)*dx));"
echo "						if (xx>mxy) mxy=xx;"
echo "						else if (xx<mny) mny=xx;"
echo "					}"
echo "				}"
echo "				else/* multiplot over k */"
echo "				{"
echo "					{nx=g_array_sized_new(FALSE, FALSE, sizeof(gint), kdimxf); sz=g_array_sized_new(FALSE, FALSE, sizeof(gint), kdimxf); st=g_array_sized_new(FALSE, FALSE, sizeof(gint), kdimxf);}"
echo "					dx2+=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jind2))*kdimxf;"
echo "					{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, dx2);}"
echo "					mny=g_array_index(y, gdouble, dx2);"
echo "					{mxy=mny; l=1;}"
echo "					while (l<mx)"
echo "					{"
echo "						xx=g_array_index(y, gdouble, dx2+((l++)*dx));"
echo "						if (xx>mxy) mxy=xx;"
echo "						else if (xx<mny) mny=xx;"
echo "					}"
echo "					k=dx2+1;"
echo "					while (k<kdimxf+dx2)"
echo "					{"
echo "						{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, k);}"
echo "						l=0;"
echo "						while (l<mx)"
echo "						{"
echo "							xx=g_array_index(y, gdouble, k+((l++)*dx));"
echo "							if (xx>mxy) mxy=xx;"
echo "							else if (xx<mny) mny=xx;"
echo "						}"
echo "						k++;"
echo "					}"
echo "				}"
echo "			}"
echo "			else if ((flagd&DISP_MRK)==0)/* multiplot over j */"
echo "			{"
echo "				{nx=g_array_sized_new(FALSE, FALSE, sizeof(gint), jdimx); sz=g_array_sized_new(FALSE, FALSE, sizeof(gint), jdimx); st=g_array_sized_new(FALSE, FALSE, sizeof(gint), jdimx);}"
echo "				dx2+=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(kind));"
echo "				{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, dx2);}"
echo "				mny=g_array_index(y, gdouble, dx2);"
echo "				{mxy=mny; l=1;}"
echo "				while (l<mx)"
echo "				{"
echo "					xx=g_array_index(y, gdouble, dx2+((l++)*dx));"
echo "					if (xx>mxy) mxy=xx;"
echo "					else if (xx<mny) mny=xx;"
echo "				}"
echo "				k=dx2+kdimxf;"
echo "				while (k<dx+dx2)"
echo "				{"
echo "					{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, k);}"
echo "					l=0;"
echo "					while (l<mx)"
echo "					{"
echo "						xx=g_array_index(y, gdouble, k+((l++)*dx));"
echo "						if (xx>mxy) mxy=xx;"
echo "						else if (xx<mny) mny=xx;"
echo "					}"
echo "					k+=kdimxf;"
echo "				}"
echo "			}"
echo "			else /* both indices */"
echo "			{"
echo "				{nx=g_array_sized_new(FALSE, FALSE, sizeof(gint), dx); sz=g_array_sized_new(FALSE, FALSE, sizeof(gint), dx); st=g_array_sized_new(FALSE, FALSE, sizeof(gint), dx);}"
echo "				{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, dx2);}"
echo "				mny=g_array_index(y, gdouble, dx2);"
echo "				{mxy=mny; l=1;}"
echo "				while (l<mx)"
echo "				{"
echo "					xx=g_array_index(y, gdouble, dx2+((l++)*dx));"
echo "					if (xx>mxy) mxy=xx;"
echo "					else if (xx<mny) mny=xx;"
echo "				}"
echo "				k=dx2+1;"
echo "				while (k<dx+dx2)"
echo "				{"
echo "					{g_array_append_val(sz, mx); g_array_append_val(st, dx); g_array_append_val(nx, k);}"
echo "					l=0;"
echo "					while (l<mx)"
echo "					{"
echo "						xx=g_array_index(y, gdouble, k+((l++)*dx));"
echo "						if (xx>mxy) mxy=xx;"
echo "						else if (xx<mny) mny=xx;"
echo "					}"
echo "					k++;"
echo "				}"
echo "			}"
echo "			dialog=gtk_dialog_new_with_buttons(_(\"Measurand Variable Type\"), GTK_WINDOW(window), GTK_DIALOG_MODAL|GTK_DIALOG_DESTROY_WITH_PARENT, _(\"Linear\"), 1, _(\"Polar\\n(Degrees)\"), 2, _(\"Polar\\n(Radians)\"), 3, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, NULL);"
echo "			cont=gtk_dialog_get_content_area(GTK_DIALOG(dialog));"
echo "			label=gtk_label_new(_(\"Select Measurand Type:\"));"
echo "			gtk_container_add(GTK_CONTAINER(cont), label);"
echo "			switch (gtk_dialog_run(GTK_DIALOG(dialog)))"
echo "			{"
echo "				case 1:"
echo "				if (((flags&PROC_BAT)==0)||((flags&PROC_POL)!=0))"
echo "				{"
echo "					gtk_notebook_remove_page(GTK_NOTEBOOK(notebook2), 2);"
echo "					rest=gtk_table_new(1, 1, FALSE);"
echo "					gtk_widget_show(rest);"
echo "					plot3=gtk_plot_linear_new();"
echo "					g_signal_connect(plot3, \"moved\", G_CALLBACK(pltmv), NULL);"
echo "					gtk_widget_show(plot3);"
echo "					gtk_table_attach(GTK_TABLE(rest), plot3, 0, 1, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "					label=gtk_label_new(_(\"Analysis Results\"));"
echo "					gtk_notebook_append_page(GTK_NOTEBOOK(notebook2), rest, label);"
echo "					{flags|=(PROC_BAT|PROC_PRS|PROC_TRS|PROC_OPN); flags&=(PROC_OFT|PROC_CHP|PROC_BAT|PROC_PRS|PROC_TRS|PROC_OPN);}"
echo "				}"
echo "				plt=GTK_PLOT_LINEAR(plot3);"
echo "				if (mx<8) {(plt->flagd)=3; (plt->ptsize)=4;}"
echo "				else if (mx<20){(plt->flagd)=3; (plt->ptsize)=3;}"
echo "				else if (mx<50){(plt->flagd)=3; (plt->ptsize)=2;}"
echo "				gtk_plot_linear_set_data(plt, x, y, nx, sz, st);"
echo "				gtk_plot_linear_update_scale_pretty(plot3, xi, xf, mny, mxy);"
echo "				{g_array_unref(x); g_array_unref(y); g_array_unref(nx); g_array_unref(sz); g_array_unref(st);}"
echo "				gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook), 1);"
echo "				gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook2), 2);"
echo "				break;"
echo "				case 2:"
echo "				if (((flags&PROC_BAT)==0)||((flags&PROC_POL)==0))"
echo "				{"
echo "					gtk_notebook_remove_page(GTK_NOTEBOOK(notebook2), 2);"
echo "					rest=gtk_table_new(1, 1, FALSE);"
echo "					gtk_widget_show(rest);"
echo "					plot3=gtk_plot_polar_new();"
echo "					g_signal_connect(plot3, \"moved\", G_CALLBACK(pltmvp), NULL);"
echo "					gtk_widget_show(plot3);"
echo "					gtk_table_attach(GTK_TABLE(rest), plot3, 0, 1, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "					label=gtk_label_new(_(\"Analysis Results\"));"
echo "					gtk_notebook_append_page(GTK_NOTEBOOK(notebook2), rest, label);"
echo "					flags|=(PROC_POL|PROC_BAT|PROC_PRS|PROC_TRS|PROC_OPN);"
echo "				}"
echo "				plt2=GTK_PLOT_POLAR(plot3);"
echo "				if (mx<8) (plt2->ptsize)=4;"
echo "				else if (mx<20) (plt2->ptsize)=3;"
echo "				else if (mx<50) (plt2->ptsize)=2;"
echo "				else (plt2->flagd)=2;"
echo "				gtk_plot_polar_set_data(plt2, y, x, nx, sz, st);"
echo "				gtk_plot_polar_update_scale_pretty(plot3, mny, mxy, xi, xf);"
echo "				{g_array_unref(x); g_array_unref(y); g_array_unref(nx); g_array_unref(sz); g_array_unref(st);}"
echo "				gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook), 1);"
echo "				gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook2), 2);"
echo "				break;"
echo "				case 3:"
echo "				if (((flags&PROC_BAT)==0)||((flags&PROC_POL)==0))"
echo "				{"
echo "					gtk_notebook_remove_page(GTK_NOTEBOOK(notebook2), 2);"
echo "					rest=gtk_table_new(1, 1, FALSE);"
echo "					gtk_widget_show(rest);"
echo "					plot3=gtk_plot_polar_new();"
echo "					g_signal_connect(plot3, \"moved\", G_CALLBACK(pltmvp), NULL);"
echo "					gtk_widget_show(plot3);"
echo "					gtk_table_attach(GTK_TABLE(rest), plot3, 0, 1, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "					label=gtk_label_new(_(\"Analysis Results\"));"
echo "					gtk_notebook_append_page(GTK_NOTEBOOK(notebook2), rest, label);"
echo "					flags|=(PROC_POL|PROC_BAT|PROC_PRS|PROC_TRS|PROC_OPN);"
echo "				}"
echo "				plt2=GTK_PLOT_POLAR(plot3);"
echo "				if (mx<8) {(plt2->flagd)=7; (plt2->ptsize)=4;}"
echo "				else if (mx<20) {(plt2->flagd)=7; (plt2->ptsize)=3;}"
echo "				else if (mx<50) {(plt2->flagd)=7; (plt2->ptsize)=2;}"
echo "				else (plt2->flagd)=3;"
echo "				gtk_plot_polar_set_data(plt2, y, x, nx, sz, st);"
echo "				gtk_plot_polar_update_scale_pretty(plot3, mny, mxy, xi, xf);"
echo "				{g_array_unref(x); g_array_unref(y); g_array_unref(nx); g_array_unref(sz); g_array_unref(st);}"
echo "				gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook), 1);"
echo "				gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook2), 2);"
echo "				break;"
echo "				default:"
echo "				break;"
echo "			}"
echo "			gtk_widget_destroy(dialog);"
echo "		}"
echo "		else"
echo "		{"
echo "			str=g_strdup_printf(_(\"Loading failed for file: %s, Error: %s.\"), fin, (gchar *) Err);"
echo "			gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);"
echo "			{g_free(str); g_error_free(Err);}"
echo "		}"
echo "		{g_free(contents2); g_free(fin);}"
echo "	}"
echo "}"
} >src/batc.c
