#!/bin/bash
str0="for (j=0; j<jdimx; j++)
{
	delf=g_array_index(plt->xdata, gdouble, (2*j*sz4)+1)-g_array_index(plt->xdata, gdouble, 2*j*sz4);
	if (iv<DZE) idelf=G_MAXDOUBLE;
	else idelf=1/delf;
	vzt=g_array_index(plt->ydata, gdouble, 2*j*sz4);"

str1="	iv=g_array_index(zwa, gdouble, j)*idelf/2;
	for (l=1; l<iv; l++) vzt+=g_array_index(plt->ydata, gdouble, 2*(l+(j*sz4)));
	if (vzt<DZE) vzt=G_MAXDOUBLE;
	else vzt=l/vzt;
	for (k=0; k<kdimxf; k++)
	{
		sr=(gint) ceil(g_array_index(isra, gdouble, j+(k*jdimx))*idelf);
		sp=(gint) floor(g_array_index(ispa, gdouble, j+(k*jdimx))*idelf);"

str2="		tcn=g_array_index(tca, gdouble, j+(k*jdimx))*idelf;
		twd=g_array_index(twa, gdouble, j+(k*jdimx))*idelf/2;
		if ((sr<(sz4-2))&&(sp<sz4)&&((sp-sr)>1))
		{
			vt=g_array_index(plt->ydata, gdouble, 2*(sr+(j*sz4)));
			phia=g_array_index(plt->ydata, gdouble, 1+(2*(sr+(j*sz4))));
			vt+=g_array_index(plt->ydata, gdouble, 2*(1+sr+(j*sz4)));
			phio=-g_array_index(plt->ydata, gdouble, 1+(2*(1+sr+(j*sz4))));
			phia+=phio;
			{pn=0; cn=0; dst=0; ddp=0;}
			for (l=sr+2; l<=sp; l++)
			{
				vt+=g_array_index(plt->ydata, gdouble, 2*(l+(j*sz4)));
				phi=g_array_index(plt->ydata, gdouble, 1+(2*(l+(j*sz4))));
				phio+=phi;
				if (phio>G_PI) phio-=(MY_2PI);
				else if (phio<=NMY_PI) phio+=(MY_2PI);
				if (l>(tcn-twd+0.5))
				{
					if ((l-1)<=(tcn-twd))
					{
						tp=(((gdouble) l)-tcn-0.5)/twd;
						pn+=++tp;
						dst+=tp*phio;
					}
					else if (l<=(tcn+0.5))
					{
						tp=(((gdouble) l)-tcn-0.5)/twd;
						ct=(((gdouble) l)-tcn-1)/twd;
						pn+=++tp;
						dst+=tp*phio;
						cn+=++ct;
						phia+=phio;
						ddp+=ct*phia;
					}
					else if ((l-1)<=tcn)
					{
						tp=(tcn+0.5-((gdouble) l))/twd;
						ct=(((gdouble) l)-tcn-1)/twd;
						pn+=++tp;
						dst+=tp*phio;
						cn+=++ct;
						phia+=phio;
						ddp+=ct*phia;
					}
					else if (l<(tcn+twd+0.5))
					{
						tp=(tcn+0.5-((gdouble) l))/twd;
						ct=(tcn+1-((gdouble) l))/twd;
						pn+=++tp;
						dst+=tp*phio;
						cn+=++ct;
						phia+=phio;
						ddp+=ct*phia;
					}
					else if ((l-1)<(tcn+twd))
					{
						ct=(tcn+1-((gdouble) l))/twd;
						cn+=++ct;
						phia+=phio;
						ddp+=ct*phia;
					}
				}
				phia=-phio;
				phio=-phi;
			}
			pn*=NMY_2PI*delf;
			if ((pn<DZE)&&(pn>NZE)) dst=G_MAXDOUBLE;
			else dst/=pn;
			cn*=G_PI*NMY_2PI*delf*delf;
			if ((cn<DZE)&&(cn>NZE)) ddp=G_MAXDOUBLE;
			else ddp=cn/ddp;
			vt*=vzt/(sp-sr+1);
		}
		else
		{
			str=g_strdup_printf(_(\"Insufficient windowing range in channel %d, %d.\"), j, k);
			gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
			{g_free(str); vt=0; dst=0; ddp=0;}
		}
		{g_array_append_val(vis, vt); g_array_append_val(doms, dst); g_array_append_val(chp, ddp);}
	}
}
jdim=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jind2));
kdim=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(kind));
vt=g_array_index(chp, gdouble, (kdim+(jdim*kdimxf)));
g_snprintf(s, 8, \"%f\", vt);
gtk_label_set_text(GTK_LABEL(chil), s);
flags|=(PROC_CHP|PROC_PRS);"

str3="		tcn=g_array_index(tca, gdouble, j+(k*jdimx))*idelf;
		twd=g_array_index(twa, gdouble, j+(k*jdimx))*idelf/2;
		if ((sr<(sz4-1))&&(sp<sz4)&&((sp-sr)>0))
		{
			vt=g_array_index(plt->ydata, gdouble, 2*(sr+(j*sz4)));
			phio=-g_array_index(plt->ydata, gdouble, 1+(2*(sr+(j*sz4))));
			{dst=0; pn=0;}
			for (l=sr+1; l<=sp; l++)
			{
				vt+=g_array_index(plt->ydata, gdouble, 2*(l+(j*sz4)));
				phi=g_array_index(plt->ydata, gdouble, 1+(2*(l+(j*sz4))));
				phio+=phi;
				if (phio>G_PI) phio-=(MY_2PI);
				else if (phio<=NMY_PI) phio+=(MY_2PI);
				if (l>(tcn-twd+0.5))
				{
					if (l<=(tcn+0.5))
					{
						tp=(((gdouble) l)-tcn-0.5)/twd;
						pn+=++tp;
						dst+=tp*phio;
					}
					else if (l<(tcn+twd+0.5))
					{
						tp=(tcn+0.5-((gdouble) l))/twd;
						pn+=++tp;
						dst+=tp*phio;
					}
				}
				phio=-phi;
			}
			pn*=NMY_2PI*delf;
			dst=dst/pn;
			vt*=vzt/(sp-sr+1);
		}
		else
		{
			str=g_strdup_printf(_(\"Insufficient windowing range in channel %d, %d.\"), j, k);
			gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
			{g_free(str); vt=0; dst=0;}
		}
		g_array_append_val(vis, vt);
		g_array_append_val(doms, dst);
	}
}
jdim=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jind2));
kdim=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(kind));
gtk_label_set_text(GTK_LABEL(chil), \"\");
flags|=PROC_PRS;"

str5="iv=g_array_index(bsra, gdouble, j);
k=0;
while ((k<sz4)&&(iv>g_array_index((plt->xdata), gdouble, trc+(k*satl)))) k++;
sr=k;
iv=g_array_index(bspa, gdouble, j);
while ((k<sz4)&&(iv>g_array_index((plt->xdata), gdouble, trc+(k*satl)))) k++;
sp=k-sr;
if (sp>zp)
{
	str=g_strdup_printf(_(\"Some clipping occured in channel %d. Increase zero padding.\"), j);
	gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
	{sp=zp; g_free(str);}
}"

str6="if (sp<16) {ofs=g_array_index((plt->ydata), gdouble, trc+(sr*satl)); ofe=g_array_index((plt->ydata), gdouble, trc+((sp+sr-1)*satl));}
else
{
	{ofs=g_array_index((plt->ydata), gdouble, trc+(sr*satl)); ofe=g_array_index((plt->ydata), gdouble, trc+((sp+sr-1)*satl)); k=1;}
	while (k<8)
	{
		ofs+=g_array_index((plt->ydata), gdouble, trc+((sr+k)*satl));
		ofe+=g_array_index((plt->ydata), gdouble, trc+((sp+sr-(++k))*satl));
	}
	{ofs/=8; ofe/=8;}
}"

str7="iv=(sp-1)/(zp*(g_array_index((plt->xdata), gdouble, trc+(satl*(sp+sr-1)))-g_array_index((plt->xdata), gdouble, trc+(satl*sr))));
g_array_append_val(delf, iv);"

str8="if ((ofs<DZE)&&(ofs>NZE))
{
	str=g_strdup(_(\"Offset must be nonzero for linear measurements.\"));
	gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);
	g_free(str);
}"

{
echo "/***************************************************************************"
echo " *            proc.c"
echo " *"
echo " *  Sat Dec  4 17:18:14 2010"
echo " *  Copyright  2010  Paul Childs"
echo " *  <pchilds@physics.org>"
echo " ****************************************************************************/"
echo ""
echo "/*"
echo " * This program is free software; you can redistribute it and/or modify"
echo " * it under the terms of the GNU General Public License as published by"
echo " * the Free Software Foundation; either version 2 of the License, or"
echo " * (at your option) any later version."
echo " *"
echo " * This program is distributed in the hope that it will be useful,"
echo " * but WITHOUT ANY WARRANTY; without even the implied warranty of"
echo " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
echo " * GNU Library General Public License for more details."
echo " *"
echo " * You should have received a copy of the GNU General Public License"
echo " * along with this program; if not, write to the Free Software"
echo " * Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, MA 02110-1301,  USA"
echo " */"
echo ""
echo "#include \"proc.h\""
echo ""
echo "void prs(GtkWidget *widget, gpointer data)"
echo "{"
echo "	gchar *str;"
echo "	gchar s[10];"
echo "	gdouble cn, ct, ddp, delf, dst, idelf, iv, ivd, ivdt, phi, phio, phia, pn, tcn, tp, twd, vt, vzt;"
echo "	gint j, jdim, jdimx, k, kdim, l, sp, sr, sz4;"
echo "	GtkPlot *pt;"
echo "	GtkPlotLinear *plt;"
echo "	GtkWidget *label;"
echo ""
echo "	if ((flags&PROC_TRS)!=0)"
echo "	{"
echo "		pt=GTK_PLOT(plot2);"
echo "		plt=GTK_PLOT_LINEAR(plot2);"
echo "		sz4=g_array_index(pt->sizes, gint, 0);/* check placing of this with what is desired for multiplots (within for loop?) */"
echo "		jdimx=(plt->ydata->len)/(2*sz4);"
echo "		if (jdimx==(bsra->len))"
echo "		{"
echo "			if ((flags&PROC_BAT)!=0)"
echo "			{"
echo "				gtk_notebook_remove_page(GTK_NOTEBOOK(notebook2), 2);"
echo "				rest=gtk_table_new(4, 2, FALSE);"
echo "				gtk_widget_show(rest);"
echo "				label=gtk_label_new(_(\"Visibility\"));"
echo "				gtk_table_attach(GTK_TABLE(rest), label, 0, 1, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "				gtk_widget_show(label);"
echo "				visl=gtk_label_new(\"\");"
echo "				gtk_table_attach(GTK_TABLE(rest), visl, 0, 1, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "				gtk_widget_show(visl);"
echo "				label=gtk_label_new(_(\"Domain Shift\"));"
echo "				gtk_table_attach(GTK_TABLE(rest), label, 1, 2, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "				gtk_widget_show(label);"
echo "				dsl=gtk_label_new(\"\");"
echo "				gtk_table_attach(GTK_TABLE(rest), dsl, 1, 2, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "				gtk_widget_show(dsl);"
echo "				label=gtk_label_new(_(\"Chirp\"));"
echo "				gtk_table_attach(GTK_TABLE(rest), label, 0, 1, 2, 3, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "				gtk_widget_show(label);"
echo "				chil=gtk_label_new(\"\");"
echo "				gtk_table_attach(GTK_TABLE(rest), chil, 0, 1, 3, 4, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "				gtk_widget_show(chil);"
echo "				label=gtk_label_new(_(\"Analysis Results\"));"
echo "				gtk_notebook_append_page(GTK_NOTEBOOK(notebook2), rest, label);"
echo "				flags^=PROC_BAT;"
echo "			}"
echo "			{g_array_free(vis, FALSE); g_array_free(doms, FALSE); g_array_free(chp, FALSE);}"
echo "			kdimxf=(isra->len)/jdimx;"
echo "			{vis=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx*kdimxf); doms=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx*kdimxf); chp=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx*kdimxf);}"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(opttri)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(chi)))"
echo "				{"
echo "${str0}"
echo "						/*"
echo "						 fit values to zwa"
echo "						 */"
echo "${str1}"
echo "							/*"
echo "							 fit values to twa and tca"
echo "							 */"
echo "${str2}"
echo "				}"
echo "				else"
echo "				{"
echo "${str0}"
echo "						/*"
echo "						 fit values to zwa"
echo "						 */"
echo "${str1}"
echo "							/*"
echo "							 fit values to twa and tca"
echo "							 */"
echo "${str3}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(chi)))"
echo "			{"
echo "${str0}"
echo "${str1}"
echo "${str2}"
echo "			}"
echo "			else"
echo "			{"
echo "${str0}"
echo "${str1}"
echo "${str3}"
echo "			}"
echo "			vt=g_array_index(vis, gdouble, (kdim+(jdim*kdimxf)));"
echo "			g_snprintf(s, 7, \"%f\", vt);"
echo "			gtk_label_set_text(GTK_LABEL(visl), s);"
echo "			vt=g_array_index(doms, gdouble, (kdim+(jdim*kdimxf)));"
echo "			g_snprintf(s, 9, \"%f\", vt);"
echo "			gtk_label_set_text(GTK_LABEL(dsl), s);"
echo "			gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook2), 2);"
echo "		}"
echo "		else"
echo "		{"
echo "			str=g_strdup_printf(_(\"Parameter array dimensions (%d) do not match transformed data (%d).\"), (bsra->len), jdimx);"
echo "			gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);"
echo "			g_free(str);"
echo "		}"
echo "	}"
echo "	else"
echo "	{"
echo "		str=g_strdup(_(\"No transform for analysis exists yet.\"));"
echo "		gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);"
echo "		g_free(str);"
echo "	}"
echo "}"
echo ""
echo "void trs(GtkWidget *widget, gpointer data) /* need to incorporate case for inversion to 2pi/x */"
echo "{"
echo "	double *star, *yt;"
echo "	fftw_plan p;"
echo "	fftw_r2r_kind type=FFTW_R2HC;"
echo "	GArray *delf, *nx, *st, *sz, *x, *y;"
echo "	gchar *str;"
echo "	gdouble ce, clc, iv, iv2, ofe, ofs, xx, yx;"
echo "	gint dx, dx2, j, jdim, jdimx, k, n, satl, sp, sr, sz4, trc, zp;"
echo "	GtkPlot *pt;"
echo "	GtkPlotLinear *plt;"
echo "	GtkWidget *label;"
echo ""
echo "	if ((flags&PROC_OPN)!=0)"
echo "	{"
echo "		if ((flags&PROC_BAT)!=0)"
echo "		{"
echo "			gtk_notebook_remove_page(GTK_NOTEBOOK(notebook2), 2);"
echo "			rest=gtk_table_new(4, 2, FALSE);"
echo "			gtk_widget_show(rest);"
echo "			label=gtk_label_new(_(\"Visibility\"));"
echo "			gtk_table_attach(GTK_TABLE(rest), label, 0, 1, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(label);"
echo "			visl=gtk_label_new(\"\");"
echo "			gtk_table_attach(GTK_TABLE(rest), visl, 0, 1, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(visl);"
echo "			label=gtk_label_new(_(\"Domain Shift\"));"
echo "			gtk_table_attach(GTK_TABLE(rest), label, 1, 2, 0, 1, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(label);"
echo "			dsl=gtk_label_new(\"\");"
echo "			gtk_table_attach(GTK_TABLE(rest), dsl, 1, 2, 1, 2, GTK_FILL|GTK_SHRINK|GTK_EXPAND, GTK_FILL|GTK_SHRINK|GTK_EXPAND, 2, 2);"
echo "			gtk_widget_show(dsl);"
echo "			label=gtk_label_new(_(\"Analysis Results\"));"
echo "			gtk_notebook_append_page(GTK_NOTEBOOK(notebook2), rest, label);"
echo "			flags^=PROC_BAT;"
echo "		}"
echo "		jdimx=bsra->len;"
echo "		delf=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), jdimx);"
echo "		zp=1<<(gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(zpd)));"
echo "		n=zp*jdimx;"
echo "		yt=fftw_malloc(sizeof(double)*n);"
echo "		plt=GTK_PLOT_LINEAR(plot1);"
echo "		pt=GTK_PLOT(plot1);"
echo "		{trc=g_array_index(pt->ind, gint, 0); satl=g_array_index(pt->stride, gint, 0); sz4=g_array_index(pt->sizes, gint, 0);}"
echo "		ce=0;"
echo "		for (j=1; j<=16; j++) ce+=g_array_index((plt->ydata), gdouble, trc+((sz4-j)*satl));"
echo "		ce/=16;"
echo "		for (j=0; j<n; j++) yt[j]=0;"
echo "		if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(twopionx)))/* interpolate */"
echo "		{"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(wll)))/* window based offset */"
echo "			{"
echo "				flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBss- */"
echo "							{"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str5}"
echo "									/* fill array */"
echo "								}"
echo "							}"
echo "							else /* +TdBss- */"
echo "							{"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str5}"
echo "									/* fill array */"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBss- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "						else /* +RdBss- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlss- and +Tlss- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "					else /* -Rlss- +Rlss- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "						else /* +TdB0- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "					else /* +RdB0- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0- and +Tl0- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "				else /* -Rl0- +Rl0- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "						iv=g_array_index(bsra, gdouble, j);"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(oft)))/* history based offset */"
echo "			{"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				if ((flags&PROC_OFT)!=0)"
echo "				{"
echo "					ofs+=ce-oe;"
echo "					gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), ofs);"
echo "				}"
echo "				else flags|=PROC_OFT;"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "						{"
echo "							if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBss- */"
echo "							{"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str5}"
echo "									/* fill array */"
echo "								}"
echo "							}"
echo "							else /* +TdBss- */"
echo "							{"
echo "								for (j=0; j<jdimx; j++)"
echo "								{"
echo "${str5}"
echo "									/* fill array */"
echo "								}"
echo "							}"
echo "						}"
echo "						else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBss- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "						else /* +RdBss- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlss- and +Tlss- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "					else /* -Rlss- +Rlss- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "						else /* +TdB0- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "					else /* +RdB0- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0- and +Tl0- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "				else /* -Rl0- +Rl0- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))/* user defined offset */"
echo "			{"
echo "				flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBss- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "						else /* +TdBss- */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "								/* fill array */"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBss- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "					else /* +RdBss- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlss- +Tlss- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "				else /* -Rlss- +Rlss- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "			{"
echo "				flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "					else /* +TdB0- */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "							/* fill array */"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "				else /* +RdB0- */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "						/* fill array */"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0- +Tl0- */"
echo "			{"
echo "				flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "					/* fill array */"
echo "				}"
echo "			}"
echo "			else /* -Rl0- +Rl0- */"
echo "			{"
echo "				flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "					/* fill array */"
echo "				}"
echo "			}"
echo "		}"
echo "		else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(wll)))/* window based offset */"
echo "		{"
echo "			flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssw+ */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "${str6}"
echo "${str7}"
echo "								for (k=0; k<sp; k++)"
echo "								{"
echo "									clc=ofs+(k*(ofe-ofs)/(sp-1))-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl));"
echo "									if (clc<NZE) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));"
echo "									else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "								}"
echo "							}"
echo "							gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), (ofs+ofe)/2);"
echo "						}"
echo "						else /* +TdBssw+ */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "${str6}"
echo "${str7}"
echo "								for (k=0; k<sp; k++)"
echo "								{"
echo "									clc=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs-(k*(ofe-ofs)/(sp-1));"
echo "									if (clc<NZE) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));"
echo "									else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "								}"
echo "							}"
echo "							gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), (ofs+ofe)/2);"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssw+ */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl)));"
echo "						}"
echo "					}"
echo "					else /* +RdBssw+ */"
echo "					{"
echo "						ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs);"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssw+ +Tlssw+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str6}"
echo "${str7}"
echo "						for (k=0; k<sp; k++)"
echo "						{"
echo "							clc=ofs+(k*(ofe-ofs)/(sp-1));"
echo "							if (clc<DZE && clc>NZE) yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "							else"
echo "							{"
echo "								clc=1-(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/clc);"
echo "								if (clc>DZE) yt[k+(j*zp)]=log(clc);"
echo "								else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "							}"
echo "						}"
echo "					}"
echo "					gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), (ofs+ofe)/2);"
echo "				}"
echo "				else /* -Rlssw+ +Rlssw+ */"
echo "				{"
echo "					ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++)"
echo "						{"
echo "							clc=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs;"
echo "							if (clc>0) yt[k+(j*zp)]=log(clc);"
echo "							else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "						}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0w+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str6}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(ofs+(k*(ofe-ofs)/(sp-1))-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))));"
echo "						}"
echo "						gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), (ofs+ofe)/2);"
echo "					}"
echo "					else /* +TdB0w+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str6}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs-(k*(ofe-ofs)/(sp-1))));"
echo "						}"
echo "						gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), (ofs+ofe)/2);"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0w+ */"
echo "				{"
echo "					ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))));"
echo "					}"
echo "				}"
echo "				else /* +RdB0w+ */"
echo "				{"
echo "					ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs));"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0w+ +Tl0w+ */"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str6}"
echo "${str7}"
echo "					for (k=0; k<sp; k++)"
echo "					{"
echo "						clc=ofs+(k*(ofe-ofs)/(sp-1));"
echo "						if (clc<DZE && clc>NZE) yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "						else yt[k+(j*zp)]=1-(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/clc);"
echo "					}"
echo "				}"
echo "				gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), (ofs+ofe)/2);"
echo "			}"
echo "			else /* -Rl0w+ +Rl0w+ */"
echo "			{"
echo "				ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs;"
echo "				}"
echo "			}"
echo "		}"
echo "		else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(oft)))/* history based offset */"
echo "		{"
echo "			ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "			if ((flags&PROC_OFT)!=0)"
echo "			{"
echo "				ofs+=ce-oe;"
echo "				gtk_spin_button_set_value(GTK_SPIN_BUTTON(fst), ofs);"
echo "			}"
echo "			else flags|=PROC_OFT;"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "					{"
echo "						if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBssh+ */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "${str7}"
echo "								for (k=0; k<sp; k++)"
echo "								{"
echo "									clc=ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl));"
echo "									if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));"
echo "									else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "								}"
echo "							}"
echo "						}"
echo "						else /* +TdBssh+ */"
echo "						{"
echo "							for (j=0; j<jdimx; j++)"
echo "							{"
echo "${str5}"
echo "${str7}"
echo "								for (k=0; k<sp; k++)"
echo "								{"
echo "									clc=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs;"
echo "									if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));"
echo "									else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "								}"
echo "							}"
echo "						}"
echo "					}"
echo "					else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBssh+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl)));"
echo "						}"
echo "					}"
echo "					else /* +RdBssh+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs);"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlssh+ +Tlssh+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++)"
echo "						{"
echo "							clc=1-(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs);"
echo "							if (clc>0) yt[k+(j*zp)]=log(clc);"
echo "							else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "						}"
echo "					}"
echo "				}"
echo "				else /* -Rlssh+ +Rlssh+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++)"
echo "						{"
echo "							clc=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs;"
echo "							if (clc>0) yt[k+(j*zp)]=log(clc);"
echo "							else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "						}"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0h+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))));"
echo "						}"
echo "					}"
echo "					else /* +TdB0h+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs));"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0h+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))));"
echo "					}"
echo "				}"
echo "				else /* +RdB0h+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs));"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0h+ +Tl0h+ */"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=1-(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs);"
echo "				}"
echo "			}"
echo "			else /* -Rl0h+ +Rl0h+ */"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs;"
echo "				}"
echo "			}"
echo "		}"
echo "		else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(lcmp)))/* user defined offset */"
echo "		{"
echo "			flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "			ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "				{"
echo "					if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdBsso+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++)"
echo "							{"
echo "								clc=ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl));"
echo "								if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));"
echo "								else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "							}"
echo "						}"
echo "					}"
echo "					else /* +TdBsso+ */"
echo "					{"
echo "						for (j=0; j<jdimx; j++)"
echo "						{"
echo "${str5}"
echo "${str7}"
echo "							for (k=0; k<sp; k++)"
echo "							{"
echo "								clc=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs;"
echo "								if (clc<0) yt[k+(j*zp)]=log(1-exp(LNTOT*clc));"
echo "								else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "							}"
echo "						}"
echo "					}"
echo "				}"
echo "				else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdBsso+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl)));"
echo "					}"
echo "				}"
echo "				else /* +RdBsso+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=0.1*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs);"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tlsso+ +Tlsso+ */"
echo "			{"
echo "${str8}"
echo "				else"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++)"
echo "						{"
echo "							clc=1-(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs);"
echo "							if (clc>0) yt[k+(j*zp)]=log(clc);"
echo "							else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "						}"
echo "					}"
echo "				}"
echo "			}"
echo "			else /* -Rlsso+ +Rlsso+ */"
echo "			{"
echo "${str8}"
echo "				else"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++)"
echo "						{"
echo "							clc=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs;"
echo "							if (clc>0) yt[k+(j*zp)]=log(clc);"
echo "							else yt[k+(j*zp)]=-G_MAXDOUBLE;"
echo "						}"
echo "					}"
echo "				}"
echo "			}"
echo "		}"
echo "		else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(dBs)))"
echo "		{"
echo "			flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "			ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "			if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans)))"
echo "			{"
echo "				if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -TdB0o+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))));"
echo "					}"
echo "				}"
echo "				else /* +TdB0o+ */"
echo "				{"
echo "					for (j=0; j<jdimx; j++)"
echo "					{"
echo "${str5}"
echo "${str7}"
echo "						for (k=0; k<sp; k++) yt[k+(j*zp)]=1-exp(LNTOT*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs));"
echo "					}"
echo "				}"
echo "			}"
echo "			else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(neg))) /* -RdB0o+ */"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(ofs-g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))));"
echo "				}"
echo "			}"
echo "			else /* +RdB0o+ */"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=exp(LNTOT*(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))-ofs));"
echo "				}"
echo "			}"
echo "		}"
echo "		else if (gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(trans))) /* -Tl0o+ and +Tl0o+ */"
echo "		{"
echo "			flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "			ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "${str8}"
echo "			else"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=1-(g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs);"
echo "				}"
echo "			}"
echo "		}"
echo "		else /* -Rl0o+ and +Rl0o+ */"
echo "		{"
echo "			flags&=(PROC_OPN|PROC_TRS|PROC_PRS|PROC_BAT|PROC_CHP|PROC_POL|PROC_COM|PROC_RI);"
echo "			ofs=gtk_spin_button_get_value(GTK_SPIN_BUTTON(fst));"
echo "${str8}"
echo "			else"
echo "			{"
echo "				for (j=0; j<jdimx; j++)"
echo "				{"
echo "${str5}"
echo "${str7}"
echo "					for (k=0; k<sp; k++) yt[k+(j*zp)]=g_array_index((plt->ydata), gdouble, trc+((k+sr)*satl))/ofs;"
echo "				}"
echo "			}"
echo "		}"
echo "		star=fftw_malloc(sizeof(double)*n);"
echo "		p=fftw_plan_many_r2r(1, &zp, jdimx, yt, NULL, 1, zp, star, NULL, 1, zp, &type, FFTW_ESTIMATE);"
echo "		fftw_execute(p);"
echo "		{fftw_destroy_plan(p); fftw_free(yt);}"
echo "		{n>>=1; dx=zp>>1;}"
echo "		{x=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), n); y=g_array_sized_new(FALSE, FALSE, sizeof(gdouble), n);}"
echo "		xx=0;"
echo "		g_array_append_val(x, xx);"
echo "		g_array_append_val(x, xx);"
echo "		iv=fabs(star[0]);"
echo "		g_array_append_val(y, iv);"
echo "		g_array_append_val(y, xx);"
echo "		for (j=1; j<dx; j++)"
echo "		{"
echo "			xx=j*g_array_index(delf, gdouble, 0);"
echo "			g_array_append_val(x, xx);"
echo "			g_array_append_val(x, xx);"
echo "			{iv=star[j]; clc=star[zp-j];}"
echo "			iv2=atan2(iv, clc);"
echo "			iv=sqrt((iv*iv)+(clc*clc));"
echo "			g_array_append_val(y, iv);"
echo "			g_array_append_val(y, iv2);"
echo "		}"
echo "		k=1;"
echo "		while (k<jdimx)"
echo "		{"
echo "			xx=0;"
echo "			g_array_append_val(x, xx);"
echo "			g_array_append_val(x, xx);"
echo "			iv=fabs(star[k*zp]);"
echo "			g_array_append_val(y, iv);"
echo "			g_array_append_val(y, xx);"
echo "			for (j=1; j<dx; j++)"
echo "			{"
echo "				xx=j*g_array_index(delf, gdouble, 0);"
echo "				g_array_append_val(x, xx);"
echo "				{iv=star[j+(k*zp)]; clc=star[((k+1)*zp)-j];}"
echo "				iv2=atan2(iv, clc);"
echo "				iv=sqrt((iv*iv)+(clc*clc));"
echo "				g_array_append_val(y, iv);"
echo "				g_array_append_val(y, iv2);"
echo "			}"
echo "			k++;"
echo "		}"
echo "		{fftw_free(star); g_array_free(delf, FALSE);}"
echo "		dx2=2;"
echo "		if ((flagd&DISP_MIJ)==0)"
echo "		{"
echo "			jdim=zp*gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jind));"
echo "			{nx=g_array_new(FALSE, FALSE, sizeof(gint)); sz=g_array_new(FALSE, FALSE, sizeof(gint)); st=g_array_new(FALSE, FALSE, sizeof(gint));}"
echo "			{g_array_append_val(nx, jdim); g_array_append_val(sz, dx); g_array_append_val(st, dx2);}"
echo "			yx=g_array_index(y, gdouble, jdim);"
echo "			for (j=2; j<zp; j+=2)"
echo "			{"
echo "				iv=g_array_index(y, gdouble, j+jdim);"
echo "				if (yx<iv) yx=iv;"
echo "			}"
echo "		}"
echo "		else"
echo "		{"
echo "			{nx=g_array_sized_new(FALSE, FALSE, sizeof(gint), jdimx); sz=g_array_sized_new(FALSE, FALSE, sizeof(gint), jdimx); st=g_array_sized_new(FALSE, FALSE, sizeof(gint), jdimx);}"
echo "			for (j=0;j<(2*n);j+=zp) {g_array_append_val(nx, j); g_array_append_val(sz, dx); g_array_append_val(st, dx2);}"
echo "			yx=g_array_index(y, gdouble, 0);"
echo "			for (j=2; j<n; j+=2)"
echo "			{"
echo "				iv=g_array_index(y, gdouble, j);"
echo "				if (yx<iv) yx=iv;"
echo "			}"
echo "		}"
echo "		{oe=ce; flags|=PROC_TRS;}"
echo "		plt=GTK_PLOT_LINEAR(plot2);"
echo "		gtk_plot_linear_set_data(plt, x, y, nx, sz, st);"
echo "		{g_array_unref(x); g_array_unref(y); g_array_unref(nx); g_array_unref(sz); g_array_unref(st);}"
echo "		gtk_plot_linear_update_scale_pretty(plot2, 0, xx, 0, yx);"
echo "		{gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook), 1); gtk_notebook_set_current_page(GTK_NOTEBOOK(notebook2), 1);}"
echo "		g_signal_connect(G_OBJECT(pr), \"clicked\", G_CALLBACK(prs), NULL);"
echo "	}"
echo "	else"
echo "	{"
echo "		str=g_strdup(_(\"Open a file for analysis first.\"));"
echo "		gtk_statusbar_push(GTK_STATUSBAR(statusbar), gtk_statusbar_get_context_id(GTK_STATUSBAR(statusbar), str), str);"
echo "		g_free(str);"
echo "	}"
echo "}"
} >src/proc.c
